#!/usr/bin/python

import stringcompile
import optparse
import marshal

def main():
    p = optparse.OptionParser()
    p.add_option('--verbose', '-v', action = "store_true", default = False)
    p.add_option('--no-compile', '-n', dest = "compile", action = "store_false", default = True)
    p.add_option('--includes', '-i', default = "include")
    p.add_option("--run", '-r', action = "store_true", default = False)
    options, arguments = p.parse_args()

    if len(arguments) > 0:
        with open("modules.conf","w") as conf:
            for module in arguments:
                conf.write(module + "\n")
                if options.verbose:
                    print "Added", module

    ret = None

    if options.compile:
        if options.verbose: print "Generating module"
        
        code = ""
        with open("modules.conf") as conf:
            modules = conf.read().split("\n")
            try:
                modules.remove("")
            except:
                pass

        modules = [options.includes.replace(".py","")] + modules
        
        for module in modules:
            code += "\n"
            with open(module + ".py") as f:
                code += f.read()

        if options.verbose: print "Compiling"

        stringcompile.compile(code, "attack.pyc")

        ret = code

    if options.run:
        if options.verbose: print "Running basic_combat"
        import basic_combat
        basic_combat.main()

    return ret

if __name__ == "__main__":
    main()
